spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_sda_catalog?stringtype=unspecified
    username: sda_catalog
    password: sd4_c4t4l0g
  jpa:
    hibernate:
      ddl-auto: update